#!/bin/bash
 
PACKAGE=$1
COMMAND=$2
ARGS=${@:3}

#echo "package: $PACKAGE"
#echo "command: $COMMAND"
#echo "args: $ARGS"


VENV_PATH=~/venvs/$PACKAGE
ACTIVATE_SCRIPT=~/venvs/$PACKAGE/bin/activate
BIN_PATH=/usr/bin
COMMAND_BIN_PATH=$BIN_PATH/$COMMAND

# check if venv exists
if test -d "$VENV_PATH"; then
  :
else
  # create new venv
  echo "$VENV_PATH does not exist"
  mkdir -p $VENV_PATH
  python3 -m venv $VENV_PATH
fi

# switch to venv
source "$ACTIVATE_SCRIPT"

# check if package is installed
if [[ $(pip freeze | grep $PACKAGE) ]]; then
    :
    # check for update?

else
    # check if package exists
    if [[ $(pip search $PACKAGE | cut -d' ' -f1 | grep "^${PACKAGE}\$") ]]; then
      # everything is fine
      :
    else
      echo "Package $PACKAGE does not exist"
      deactivate
      exit 1
    fi

    echo "$PACKAGE package is not installed, installing..."
    pip install $PACKAGE
fi

# check if /usr/bin script is available
if test -f "$COMMAND_BIN_PATH"; then
  :
else
  # create easy access binary
  echo "creating helper script in $BIN_PATH..."
  cat << EOL | sudo tee $COMMAND_BIN_PATH
#!/bin/bash
/usr/bin/venv-install "${PACKAGE}" "${COMMAND}" "\$@"
EOL

  sudo chmod +x $COMMAND_BIN_PATH

fi

$COMMAND $ARGS
deactivate
