#!/bin/bash

if (( $# < 2 )); then
    echo "Illegal number of parameters, usage: venv-install <PACKAGE> <COMMAND> [ARGS]"
    exit 1
fi
 
PACKAGE=$1
COMMAND=$2
ARGS=${@:3}

#echo "package: $PACKAGE"
#echo "command: $COMMAND"
#echo "args: $ARGS"


VENV_PATH=~/venvs/$PACKAGE
ACTIVATE_SCRIPT=$VENV_PATH/bin/activate
BIN_PATH=/usr/bin
COMMAND_BIN_PATH=$BIN_PATH/$COMMAND

echo "Installing '$COMMAND@$PACKAGE' ..."

# check if venv exists
if test -d "$VENV_PATH"; then
  :
else
  # create new venv
  echo "Creating new venv '$VENV_PATH' ..."
  mkdir -p $VENV_PATH
  python3 -m venv $VENV_PATH
fi

# switch to venv
source "$ACTIVATE_SCRIPT"

# check if package is installed
if [[ $(pip freeze | grep $PACKAGE) ]]; then
    :
    # check for update?

else
    # check if package exists
    if [[ $(pip search $PACKAGE | cut -d' ' -f1 | grep "^${PACKAGE}\$") ]]; then
      # everything is fine
      :
    else
      echo "No PyPi package with name '$PACKAGE' found"
      deactivate
      exit 1
    fi

    echo "Installing package '$PACKAGE' ..."
    pip install --upgrade pip
    pip install $PACKAGE
fi

deactivate

# check if /usr/bin script is available
if test -f "$COMMAND_BIN_PATH"; then
  :
else
  # create easy access "binary"
  echo "Creating helper run script '$COMMAND_BIN_PATH'..."
  cat << EOL | sudo tee $COMMAND_BIN_PATH
#!/bin/bash
/usr/bin/venv-run "${PACKAGE}" "${COMMAND}" "\$@"
EOL
  sudo chmod +x $COMMAND_BIN_PATH
fi
